namespace BisHelpers.web.Seeds;

public static class DefaultAcademicCourses
{
    public static readonly List<AcademicCourse> Data =
    [
        new AcademicCourse { Id = 1, Name = "Principles of Accounting 1", Code = "Acc101", CreditHours = 3 },
        new AcademicCourse { Id = 2, Name = "Principles of Accounting 2", Code = "Acc102", CreditHours = 3 },
        new AcademicCourse { Id = 3, Name = "Accounting for Partnerships", Code = "Acc201", CreditHours = 3 },
        new AcademicCourse { Id = 4, Name = "Accounting for Corporations", Code = "Acc202", CreditHours = 3 },
        new AcademicCourse { Id = 5, Name = "Principle of Economics", Code = "Eco101", CreditHours = 3 },
        new AcademicCourse { Id = 6, Name = "Economics of Money and Banking", Code = "Eco201", CreditHours = 3 },
        new AcademicCourse { Id = 7, Name = "Principles of Management", Code = "Man101", CreditHours = 3 },
        new AcademicCourse { Id = 8, Name = "Behavior Management", Code = "Man102", CreditHours = 3 },
        new AcademicCourse { Id = 9, Name = "Production and Operations Management", Code = "Man201", CreditHours = 3 },
        new AcademicCourse { Id = 10, Name = "Management of Marketing", Code = "Man202", CreditHours = 3 },
        new AcademicCourse { Id = 11, Name = "Marketing", Code = "Mmt101", CreditHours = 3 },
        new AcademicCourse { Id = 12, Name = "Statistics", Code = "Sta201", CreditHours = 3 },
        new AcademicCourse { Id = 13, Name = "Cost Accounting", Code = "Acc301", CreditHours = 3 },
        new AcademicCourse { Id = 14, Name = "Principles of Auditing", Code = "Acc292", CreditHours = 3 },
        new AcademicCourse { Id = 15, Name = "Managerial Accounting", Code = "Acc491", CreditHours = 3 },
        new AcademicCourse { Id = 16, Name = "Financial Management and Investment", Code = "Man301", CreditHours = 3 },
        new AcademicCourse { Id = 17, Name = "Human Resources Management", Code = "Man302", CreditHours = 3 },
        new AcademicCourse { Id = 18, Name = "Tax Accounting", Code = "Acc391", CreditHours = 3 },
        new AcademicCourse { Id = 19, Name = "Accounting in Financial Institutions", Code = "Acc492", CreditHours = 3 },
        new AcademicCourse { Id = 20, Name = "The Economics of Foreign Trade", Code = "Eco292", CreditHours = 3 },
        new AcademicCourse { Id = 21, Name = "Economic Planning", Code = "Eco392", CreditHours = 3 },
        new AcademicCourse { Id = 22, Name = "Economics of Public Finance", Code = "Eco393", CreditHours = 3 },
        new AcademicCourse { Id = 23, Name = "Economics of Information", Code = "Eco401", CreditHours = 3 },
        new AcademicCourse { Id = 24, Name = "Material Management", Code = "Man203", CreditHours = 3 },
        new AcademicCourse { Id = 25, Name = "Management of Specialized Institutions", Code = "Man303", CreditHours = 3 },
        new AcademicCourse { Id = 26, Name = "International Relations", Code = "Pos201", CreditHours = 3 },
        new AcademicCourse { Id = 27, Name = "Introduction to Computer", Code = "BIS101", CreditHours = 3 },
        new AcademicCourse { Id = 28, Name = "Information Systems", Code = "BIS103", CreditHours = 3 },
        new AcademicCourse { Id = 29, Name = "Programming 1", Code = "BIS201", CreditHours = 3 },
        new AcademicCourse { Id = 30, Name = "Operative Systems", Code = "BIS203", CreditHours = 3 },
        new AcademicCourse { Id = 31, Name = "System Analysis 1", Code = "BIS303", CreditHours = 3 },
        new AcademicCourse { Id = 32, Name = "System Analysis 2", Code = "BIS304", CreditHours = 3 },
        new AcademicCourse { Id = 33, Name = "Programming 2", Code = "BIS307", CreditHours = 3 },
        new AcademicCourse { Id = 34, Name = "Database", Code = "BIS302", CreditHours = 3 },
        new AcademicCourse { Id = 35, Name = "E-Commerce", Code = "BIS305", CreditHours = 3 },
        new AcademicCourse { Id = 36, Name = "Management Information Systems", Code = "BIS306", CreditHours = 3 },
        new AcademicCourse { Id = 37, Name = "Operations Research", Code = "BIS310", CreditHours = 3 },
        new AcademicCourse { Id = 38, Name = "Decision Support System", Code = "BIS402", CreditHours = 3 },
        new AcademicCourse { Id = 39, Name = "Computer Networks", Code = "BIS403", CreditHours = 3 },
        new AcademicCourse { Id = 40, Name = "Data Security", Code = "BIS405", CreditHours = 3 },
        new AcademicCourse { Id = 41, Name = "Project 1", Code = "BIS412", CreditHours = 3 },
        new AcademicCourse { Id = 42, Name = "Project 2", Code = "BIS413", CreditHours = 3 },
        new AcademicCourse { Id = 43, Name = "E-Commerce Sites", Code = "BIS308", CreditHours = 3 },
        new AcademicCourse { Id = 44, Name = "Medical Information Systems and Health", Code = "BIS309", CreditHours = 3 },
        new AcademicCourse { Id = 45, Name = "Internet Applications", Code = "BIS601", CreditHours = 3 },
        new AcademicCourse { Id = 46, Name = "Advanced E-Commerce", Code = "BIS606", CreditHours = 3 },
        new AcademicCourse { Id = 47, Name = "Accounting Information Systems", Code = "BIS407", CreditHours = 3 },
        new AcademicCourse { Id = 48, Name = "Advanced Systems Analysis", Code = "BIS408", CreditHours = 3 },
        new AcademicCourse { Id = 49, Name = "Software Engineering", Code = "BIS409", CreditHours = 3 },
        new AcademicCourse { Id = 50, Name = "Project Management", Code = "BIS410", CreditHours = 3 },
        new AcademicCourse { Id = 51, Name = "English 1", Code = "HU111", CreditHours = 2 },
        new AcademicCourse { Id = 52, Name = "English 2", Code = "HU112", CreditHours = 2 },
        new AcademicCourse { Id = 54, Name = "Professional Ethics", Code = "HU334", CreditHours = 3 },
        new AcademicCourse { Id = 55, Name = "Human Rights", Code = "HU313", CreditHours = 2 },
        new AcademicCourse { Id = 56, Name = "Principle of Law", Code = "HU210", CreditHours = 3 },
        new AcademicCourse { Id = 57, Name = "Communication & Negotiation", Code = "HU331", CreditHours = 3 },
        new AcademicCourse { Id = 58, Name = "Creative Thinking", Code = "HU332", CreditHours = 3 },
        new AcademicCourse { Id = 59, Name = "Media", Code = "HU333", CreditHours = 3 },
    ];
}
