global using System.ComponentModel.DataAnnotations;
global using System.Text.Json.Serialization;
global using BisHelpers.Domain.Consts;
global using BisHelpers.Domain.Dtos.AcademicLecture;
global using BisHelpers.Domain.Dtos.Professor;
global using BisHelpers.Domain.Entities;
global using BisHelpers.Domain.Entities.RelatedData;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.EntityFrameworkCore;
